services:
  note:
    build: ./note
    container_name: note-container
    ports:
      - "8083:8083"
    networks:
      - medilabo-network
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - "SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/medilabo"
      - "SPRING_DATA_MONGODB_DATABASE=mongoDB"
      - "SPRING_DATA_MONGODB_PORT=27017"
    volumes:
      - note-data:/app/data
    restart: on-failure

  patient:
    build: ./patient
    image: medilabo_ocprojet9-patient:latest
    container_name: patient
    ports:
      - "8081:8081"
    networks:
      - medilabo-network
    depends_on:
      - mysqldb
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/medilabo"
      - "SPRING_DATASOURCE_USERNAME=root"
      - "SPRING_DATASOURCE_PASSWORD=password"
    volumes:
      - patient-data:/app/data
    restart: on-failure

  report-risk:
    build: ./risks
    container_name: report-risk-container
    ports:
      - "8084:8084"
    networks:
      - medilabo-network
    restart: on-failure

  gateway:
    build: ./gateway
    container_name: gateway-container
    ports:
      - "8080:8080"
    networks:
      - medilabo-network
    restart: on-failure

  front:
    depends_on:
      - gateway
      - patient
    build: ./clientui
    image: medilabo_ocprojet9-front:latest
    container_name: front-container
    ports:
      - "8082:8082"
    networks:
      - medilabo-network
    restart: on-failure

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - medilabo-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: "mongosh --eval 'db.runCommand(\"ping\").ok' localhost:27017 --quiet || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

  mysqldb:
    image: mysql:8.0.32
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=medilabo
    ports:
      - "3307:3306"
    networks:
      - medilabo-network
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s

networks:
  medilabo-network:
    driver: bridge

volumes:
  mongo-data:
  mysql-data:
  note-data:
  patient-data:
